### ISSUE TITLE
Unable to build "With C Standard Library" demo

### ISSUE THREAD

**Issue by warren-bank** [schellingb/ClangWasm#4]
Hi. I just found your articles on WASM and related repos.
I'm working through them in order and hit a snag.
I realize that this repo is a little old, and probably unsupported;
but I was hoping you might already know what's going on..

Here are the versions of tools that I'm using.
The .exes are newer than when you wrote your article,
and almost certainly the cause of my snag,
but I was hoping to avoid using old versions of tools..

```text
https://github.com/llvm/llvm-project/releases
https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0
https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/LLVM-13.0.0-win64.exe
  date: 2021-09-30

https://github.com/WebAssembly/binaryen/releases
https://github.com/WebAssembly/binaryen/releases/tag/version_103
https://github.com/WebAssembly/binaryen/releases/download/version_103/binaryen-version_103-x86_64-windows.tar.gz
  date: 2021-12-03

https://github.com/schellingb/ZillaLib/raw/master/Tools/make.exe
```

Here are the versions of `system` that I've used to build w/o any errors..

```text
https://github.com/emscripten-core/emscripten/releases
https://github.com/emscripten-core/emscripten/releases/tag/1.39.11
https://github.com/emscripten-core/emscripten/archive/refs/tags/1.39.11.zip
  date: 2020-03-20
  note: tag immediately preceeds most recent commit to:
        https://github.com/schellingb/ClangWasm/tree/master/LibC

https://github.com/emscripten-core/emscripten/releases/tag/1.39.19
https://github.com/emscripten-core/emscripten/archive/refs/tags/1.39.19.zip
  date: 2020-07-07
  note: most recent tag that will compile without requiring changes to makefile:
        https://github.com/schellingb/ClangWasm/blob/master/LibC/Makefile
```

The issue is that although `system/*` does successfully compile to `System.bc`,
no output is printed to the DOM when the WASM runs;
also, anecdotally, I see that my `output.wasm` is 2.6 KB whereas [yours](https://github.com/schellingb/ClangWasm/blob/master/LibC/output.wasm) is 22.2 KB

So, I suppose that I have 2x questions..

1. Do you happen to remember the exact versions of tools that you used to compile working output?
2. Do you have any thoughts on why this no-longer works?

And, while I have your attention..

* Is there any chance that you might be willing to update `Makefile` to compile a more recent copy of [`system`](https://github.com/emscripten-core/emscripten/tree/3.0.0/system)
  - sorry to ask, but this is entirely outside of my normal wheel-house

PS..

* [ZillaLib](https://zillalib.github.io/) looks amazing..
  - I can't believe the tiny size of the generated executables
    * ex: [Puzilla.apk](https://github.com/ZillaLib/zillalib.github.io/releases/download/games/Puzilla.apk) for Android is only 231 KB w/ armv7 ABI
  - hope I can figure out how to make something useful with it!

**Comment by warren-bank** [comment]
update..

I now see that your [wajic](https://github.com/schellingb/wajic) repo includes a more up-to-date [Makefile](https://github.com/schellingb/wajic/blob/3f4de6b0e7b59063b215152021941161dc7ad262/wajic.mk). With it, I was able to successfully compile the most up-to-date [`system`](https://github.com/emscripten-core/emscripten/tree/3.0.0/system) libraries. Using the resulting `system.bc` as a drop-in replacement, this demo still doesn't produce any output (to the DOM). However, I'm sure I'll be able to reproduce this demo using `wajic`.. and should be able to figure out what stopped working here.. without your assistance.. so please don't bother spending any time on this. Sorry for making noise.

**Comment by warren-bank** [comment]
additional notes for anyone interested..

<details>
  <summary>versions of tools..</summary>

  * llvm 13.0.0
    ```text
      https://github.com/llvm/llvm-project/releases
      https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0
      https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/LLVM-13.0.0-win64.exe
        date: 2021-09-30
        note: extract..
                bin/clang.exe
                bin/wasm-ld.exe
    ```
  * binaryen 103
    ```text
      https://github.com/WebAssembly/binaryen/releases
      https://github.com/WebAssembly/binaryen/releases/tag/version_103
      https://github.com/WebAssembly/binaryen/releases/download/version_103/binaryen-version_103-x86_64-windows.tar.gz
        date: 2021-12-03
        note: extract..
                binaryen-/bin/wasm-opt.exe
    ```
  * emscripten 3.0.0
    ```text
      https://github.com/emscripten-core/emscripten/releases
      https://github.com/emscripten-core/emscripten/releases/tag/3.0.0
      https://github.com/emscripten-core/emscripten/archive/refs/tags/3.0.0.zip
        date: 2021-11-22
        note: extract..
                emscripten-3.0.0/system/include
                emscripten-3.0.0/system/lib
    ```
  * make
    ```text
      https://github.com/schellingb/ZillaLib/raw/master/Tools/make.exe
    ```
</details>

<details>
  <summary>organization of tools..</summary>

  ```bash
    tree /A /F "C:\PortableApps\wasm"
  ```

  ```text
    C:\PortableApps\wasm
    |   make.exe
    |   
    +---binaryen
    |   \---103
    |           wasm-opt.exe
    |           
    +---emscripten
    |   \---3.0.0
    |       \---system
    |           +---include
    |           |   |   ...
    |           \---lib
    |               |   ...
    \---llvm
        \---13.0.0
                clang.exe
                wasm-ld.exe
  ```
</details>

<details>
  <summary>project to compile system libraries..</summary>

  * <details>
      <summary>C:\dev\LibC\LocalConfig.mk</summary>

      ```text
        LLVM_ROOT   = C:/PortableApps/wasm/llvm/13.0.0
        WASMOPT     = C:/PortableApps/wasm/binaryen/103/wasm-opt.exe
        SYSTEM_ROOT = C:/PortableApps/wasm/emscripten/3.0.0/system
      ```
    </details>

  * <details>
      <summary>C:\dev\LibC\wajic.mk</summary>

      ```bash
        wget "https://github.com/schellingb/wajic/raw/3f4de6b0e7b59063b215152021941161dc7ad262/wajic.mk"
      ```
    </details>

  * <details>
      <summary>C:\dev\LibC\compile.bat</summary>

      ```text
        @echo off

        set MAKE_HOME=C:\PortableApps\wasm
        set PATH=%MAKE_HOME%;%PATH%

        cd /D "%~dp0."
        if exist system rmdir /Q /S system
        mkdir system

        set log="%~dpn0.log"
        make -f wajic.mk -j 8 system/system.bc >%log% 2>&1
      ```
    </details>

</details>

**Comment by schellingb** [comment]
Hey there, thanks for your interest in better WASM builds :-)

Yes, as you figured out this repo is quite outdated and has basically been superseded by WAjic. The system libraries have breaking changes every few weeks. It's been hard to keep up :-)
So over on the WAjic repo you can also find pre-built system.bc libraries packaged with all the headers for both old and new llvm versions [for download there](/schellingb/wajic/releases/tag/bin). 

In many cases, WAjic can be used as a full Emscripten replacement, but being much easier to set up. I recently ported [dos-like](/mattiasgustavsson/dos-like#webassembly) to WASM with it. It's so easy to use! :-)

Though I should probably mention that in the README.md here on this repo or on the blog post.
Or update the Makefiles here, why not...

Also thanks for looking at ZillaLib. I'm always trying to make things smaller without going too crazy (getting rid of libc/libc++ would help but I'd probably go insane).
